//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO.Modelo
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BD_ticket_vs1Entities : DbContext
    {
        public BD_ticket_vs1Entities()
            : base("name=BD_ticket_vs1Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tb_area_atencion> tb_area_atencion { get; set; }
        public virtual DbSet<tb_asunto_ticket> tb_asunto_ticket { get; set; }
        public virtual DbSet<tb_categoria_ticket> tb_categoria_ticket { get; set; }
        public virtual DbSet<tb_cliente> tb_cliente { get; set; }
        public virtual DbSet<tb_estado_ticket> tb_estado_ticket { get; set; }
        public virtual DbSet<tb_modo_ticket> tb_modo_ticket { get; set; }
        public virtual DbSet<tb_nivel_ticket> tb_nivel_ticket { get; set; }
        public virtual DbSet<tb_prioridad_ticket> tb_prioridad_ticket { get; set; }
        public virtual DbSet<tb_puesto> tb_puesto { get; set; }
        public virtual DbSet<tb_responsable> tb_responsable { get; set; }
        public virtual DbSet<tb_responsable_ticket> tb_responsable_ticket { get; set; }
        public virtual DbSet<tb_ticket> tb_ticket { get; set; }
        public virtual DbSet<tb_tipo_usuario> tb_tipo_usuario { get; set; }
        public virtual DbSet<tb_ubicacion_area> tb_ubicacion_area { get; set; }
        public virtual DbSet<tb_usuario> tb_usuario { get; set; }
    }
}
