//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_area_atencion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_area_atencion()
        {
            this.tb_puesto = new HashSet<tb_puesto>();
            this.tb_responsable = new HashSet<tb_responsable>();
        }
    
        public int idArea_atencion { get; set; }
        public string cod_area_atencion { get; set; }
        public string nombre_area_atencion { get; set; }
        public int idUbicacion_area { get; set; }
    
        public virtual tb_ubicacion_area tb_ubicacion_area { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_puesto> tb_puesto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_responsable> tb_responsable { get; set; }
    }
}
