//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_responsable_ticket
    {
        public int idResponsable_ticket { get; set; }
        public int idTicket { get; set; }
        public int idResponsable { get; set; }
    
        public virtual tb_responsable tb_responsable { get; set; }
        public virtual tb_ticket tb_ticket { get; set; }
    }
}
