//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_responsable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_responsable()
        {
            this.tb_responsable_ticket = new HashSet<tb_responsable_ticket>();
        }
    
        public int idResponsable { get; set; }
        public string codresponsable { get; set; }
        public string nombre_responsable { get; set; }
        public string apellido_paterno_responsable { get; set; }
        public string apellido_materno_responsable { get; set; }
        public string telefono { get; set; }
        public string correo { get; set; }
        public int idUsuario { get; set; }
        public int idArea_atencion { get; set; }
        public int idPuesto { get; set; }
        public bool estado_responsable { get; set; }
    
        public virtual tb_area_atencion tb_area_atencion { get; set; }
        public virtual tb_puesto tb_puesto { get; set; }
        public virtual tb_usuario tb_usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_responsable_ticket> tb_responsable_ticket { get; set; }
    }
}
