//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_ubicacion_area
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_ubicacion_area()
        {
            this.tb_area_atencion = new HashSet<tb_area_atencion>();
        }
    
        public int idUbicacion_area { get; set; }
        public string cod_ubicacion_area { get; set; }
        public string nombre_edificio { get; set; }
        public string numero_piso { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_area_atencion> tb_area_atencion { get; set; }
    }
}
